### ISSUE TITLE
POSTs are broken

### ISSUE THREAD

**Issue by shaharsol** [rolandstarke/node-i18n-express-subdirs#1]
POSTS that do not contain the language portion get redirected using 303 to GET and it breaks functionality.
Moreover, I think you should also ignore xhr requests

**Comment by rolandstarke** [comment]
Hey, thanks for the report.

I am not quite sure how to solve it, one could just not redirect POST requests.


With the xhr would also be an idea too, but it would have some pitfalls if you use `Cache-Control: public, max-age=31536000`. What language is cached will be random.

**Comment by shaharsol** [comment]
Thanks.
How would you go about to apply this module only to specific routers? i.e. let's say I have an _index_ router that serves my app but also _api_ router that serves api requests and _admin_ router for back office. I want this module to apply only to _index_ router, how would you go about and do that? whatever I try doesn't work - when I apply it to any router it seems to apply to all others as well.

**Comment by rolandstarke** [comment]
For my small project I just registered the midleware after my non localized urls.
Here the static folder and /admin routes are not affected. 

```
/* serve static files */
app.use(express.static(__dirname + '/public', {
    etag: false,
    lastModified: false,
    maxAge: config.app.staticsCacheTimeSeconds * 1000,
}));
app.use(assets('/', __dirname + '/public'));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: false
}));
app.use(cookieParser());

/* set some globals to be used in the views */
app.use(function (req, res, next) {
    res.locals.req = req;
    next();
});

/* routes */
app.use('/admin', admin);
app.use(i18nSubdirs(i18n)); // language urls and redirects / -->  /en/ || /de/
app.use('/', index);
app.use('/api', api);

```

Maybe you would need to use a library with more features https://github.com/i18next/i18next-express-middleware
